### ISSUE TITLE
AST nodes uses infer_types unexpectedly

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_spa#74]
`infer_types` can use either the root network or the context type to infer a type from. However, certain classes can only use one of these options. Consequently, would it be reasonable to break the function into `infer_types_from_root(root_network)` and `infer_types_from_context(context_type)` to be explicit?

**Comment by jgosmann** [comment]
There should only be one `infer_types` method because how exactly the type is inferred depends on the type of AST node (for each node there is one specific way the inference works and you cannot chose between `from_root` and `from_context`). However, I looked through the method and it seems that the `root_network` is never actually used (if I haven't overlooked something). So potentially that argument could be deleted from the argument list. According to the documentation it is there to resolve names, but I don't think that there is a reason to resolve names in `infer_types` anymore (there might have been a reason though in the past).
